consolecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # General Routes
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # Console Routes
    path('consoles/', views.consoles_index, name='index'),
    path('consoles/<int:console_id>/', views.console_detail, name="detail"),
    path('consoles/create/', views.ConsoleCreate.as_view(), name='console_create'),
    path('consoles/<int:pk>/update/', views.ConsoleUpdate.as_view(), name="console_update"),
    path('consoles/<int:pk>/delete/', views.ConsoleDelete.as_view(), name="console_delete"),
    # Accessory Routes
    path('consoles/<int:console_id>/add_accessory', views.add_accessory, name='add_accessory'),
    # Games Routes
    path('games/', views.GameList.as_view(), name='games_index'),
    path('games/<int:pk>/', views.GameDetail.as_view(), name='game_detail'),
    path('games/create/', views.GameCreate.as_view(), name='game_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='game_update'),
    path('games/<int:pk>/delete', views.GameDelete.as_view(), name='game_delete'),
    path('consoles/<int:console_id>/assoc_game/<int:game_id>/', views.assoc_game, name="assoc_game"),
    path('consoles/<int:console_id>/unassoc_game/<int:game_id>/', views.unassoc_game, name="unassoc_game"),
    # Signup Route
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

ACCESSORIES = (
    ('C', 'Controller'),
    ('M', 'Memory Card'),
    ('E', 'External Hard Drive')
)

# Create your models here.
class Game(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    release_year = models.IntegerField('Release Year')

    def __str__(self):
        return f"{self.name} is a {self.genre} type of game released in {self.release_year}"

    def get_absolute_url(self):
        return reverse('game_detail', kwargs={'pk':self.id})

class Console(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    games = models.ManyToManyField(Game)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"A {self.brand} {self.name} from {self.year}, {self.description}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'console_id': self.id})

class Accessory(models.Model):
    name = models.CharField(
        max_length=1,
        choices=ACCESSORIES,
        default=ACCESSORIES[0][0]
        )
    number = models.IntegerField()
    date_purchased = models.DateField('Date purchased')
    console = models.ForeignKey(Console, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.number} {self.get_name_display()} purchased on {self.date_purchased}"

    class Meta:
        ordering = ['-date_purchased']

main_app/forms.py
from django.forms import ModelForm
from .models import Accessory

class AccessoryForm(ModelForm):
    class Meta:
        model = Accessory
        fields = ['name', 'number', 'date_purchased']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Console, Game
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import AccessoryForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def consoles_index(request):
    consoles = Console.objects.filter(user=request.user)
    return render(request, 'consoles/index.html', {'consoles' : consoles})

@login_required
def console_detail(request, console_id):
    console = Console.objects.get(id=console_id)
    games_console_doesnt_have = Game.objects.exclude(id__in = console.games.all().values_list('id'))
    accessory_form = AccessoryForm()
    return render(request, 'consoles/detail.html', { 
        'console' : console,
        'accessory_form': accessory_form,
        'games': games_console_doesnt_have
        })

class ConsoleCreate(LoginRequiredMixin, CreateView):
    model = Console
    fields = ['name', 'brand', 'description', 'year']

    def form_valid(self, form):
        # Assign the loggin the user (self.request.user)
        form.instance.user = self.request.user
        # Let CreateView continue to do its job
        return super().form_valid(form)

class ConsoleUpdate(LoginRequiredMixin, UpdateView):
    model = Console
    fields = ['description']

class ConsoleDelete(LoginRequiredMixin, DeleteView):
    model = Console
    success_url = '/consoles/'

@login_required
def add_accessory(request, console_id):
    form = AccessoryForm(request.POST)
    if form.is_valid():
        new_accessory = form.save(commit=False)
        new_accessory.console_id = console_id
        new_accessory.save()
    return redirect('detail', console_id=console_id)

class GameList(LoginRequiredMixin, ListView):
  model = Game

class GameDetail(LoginRequiredMixin, DetailView):
  model = Game

class GameCreate(LoginRequiredMixin, CreateView):
  model = Game
  fields = '__all__'

class GameUpdate(LoginRequiredMixin, UpdateView):
  model = Game
  fields = ['name', 'genre']

class GameDelete(LoginRequiredMixin, DeleteView):
  model = Game
  success_url = '/games/'

@login_required
def assoc_game(request, console_id, game_id):
    console = Console.objects.get(id = console_id)
    console.games.add(game_id)
    return redirect('detail', console_id = console_id)

@login_required
def unassoc_game(request, console_id, game_id):
    console = Console.objects.get(id = console_id)
    console.games.remove(game_id)
    return redirect('detail', console_id = console_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('games_index')
        else:
            error_message = 'Invalid sign up - try again'
    # otherwise, this is a GET request or bad POST
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Game Console Collector</h1>
<hr />
<p>Hire the Game Console Collector</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Game Console Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Game Console Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'game_create' %}">Add a Game</a></li>
                        <li><a href="{% url 'games_index' %}">View All Games</a></li>
                        <li><a href="{% url 'console_create' %}">Add a Console</a></li>
                        <li><a href="{% url 'index' %}">View All My Consoles</a></li>
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2022 Game Console Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/consoles/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Console Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ console.name }}</span>
        <p>Brand: {{ console.brand }}</p>
        <p>Description: {{ console.description }}</p>
        <p>Release year: {{ console.year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'console_update' console.id %}">Update</a>
        <a href="{% url 'console_delete' console.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_accessory' console.id %}" method="POST">
        {% csrf_token %}
        {{accessory_form.as_p}}
        <input type="submit" class="btn" value="Add accessory">
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Number</th>
          <th>Date Purchased</th>
        </tr>
      </thead>
      <tbody>
        {% for accessory in console.accessory_set.all %}
        <tr>
          <td>{{accessory.get_name_display}}</td>
          <td>{{accessory.number}}</td>
          <td>{{accessory.date_purchased}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- show games associated with this console -->
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ console.name }}'s Games</h3>
    {% if console.games.count %}
      {% for game in console.games.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ game.name }} released in {{ game.release_year }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_game' console.id game.id %}" method="POST">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Games to show</h5>
    {% endif %}
  </div>

  <!-- display available games after this line -->
  <div class="col s6">
    <h3>Available Games</h3>
    {% if games.count %}
      {% for game in games.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ game.name }} released in {{ game.release_year }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_game' console.id game.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{console.name}} Already Has All Games Available</h5>
    {% endif %}
  </div>

<script>
    let selectEl = document.getElementById('id_name');
    M.FormSelect.init(selectEl);

    let dateEl = document.getElementById('id_date_purchased');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>
{% endblock %}

main_app/templates/consoles/index.html
{% extends 'base.html' %} {% block content %}

<h1>Game Console List</h1>

{% for console in consoles %}
<div class="card">
  <a href="{% url 'detail' console.id %}">
    <div class="card-content">
      <span class="card-title">{{ console.name }}</span>
      <p>Brand: {{ console.brand }}</p>
      <p>Description: {{ console.description }}</p>
      <p>Release Year: {{ console.year }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/console_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1> Delete Console </h1>

    <h4> Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn">
        <a href="{% url 'detail' console.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/console_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1> Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1> Add Console </h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Game</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'game_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/game_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Game Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ game.name }}</span>
        <p>Genre: {{ game.genre }}</p>
        <p>Release Year: {{ game.release_year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'game_update' game.id %}">Edit</a>
        <a href="{% url 'game_delete' game.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Game</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/game_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Game List</h1>

{% for game in game_list %}
  <a href="{% url 'game_detail' game.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ game.name }}</span>
            <p>Genre: {{ game.genre }}</p>
            <p>Release Year: {{ game.release_year }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}